apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agence-ingress
spec:
  tls:
    - hosts:
        - app192.168.56.8
        - api192.168.56.8
      secretName: agence-dev-tls
  rules:
    - host: app192.168.56.8
    - host: api192.168.56.8
