apiVersion: v1
kind: Secret
metadata:
  name: agence-secrets
  namespace: agence-dev
  labels:
    app: agence
    environment: dev
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "agence_dev"
  SPRING_DATASOURCE_PASSWORD: "agence_dev_pwd_123"
  POSTGRES_DB: "agence_location_dev"
  POSTGRES_USER: "agence_dev"
  POSTGRES_PASSWORD: "agence_dev_pwd_123"
  JWT_SECRET: "dev_secret_key_32_chars_minimum_!!!!"
