apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: agence
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: agence-location
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - port: 8080
      targetPort: 8080
      name: http
