services:
  backend:
    environment:
      SPRING_PROFILES_ACTIVE: prod
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G

  frontend:
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  db:
    ports: []
