apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agence-platform.fullname" . }}-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secret.SPRING_DATASOURCE_USERNAME | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.SPRING_DATASOURCE_PASSWORD | quote }}
  POSTGRES_DB: {{ .Values.secret.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.secret.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.POSTGRES_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | quote }}
