config:
  SPRING_PROFILES_ACTIVE: dev
  CORS_ALLOWED_ORIGINS: https://app-dev.example.com
  VITE_API_BASE_URL: https://api-dev.example.com/api/v1

backend:
  replicaCount: 2
frontend:
  replicaCount: 2

ingress:
  hosts:
    frontend: app-dev.example.com
    backend: api-dev.example.com
  tls:
    secretName: agence-dev-tls

hpa:
  minReplicas: 2
  maxReplicas: 6
