apiVersion: v1
kind: Secret
metadata:
  name: agence-secrets
  namespace: agence-staging
  labels:
    app: agence
    environment: staging
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "agence_staging"
  SPRING_DATASOURCE_PASSWORD: "agence_staging_pwd_secure_2024"
  POSTGRES_DB: "agence_location_staging"
  POSTGRES_USER: "agence_staging"
  POSTGRES_PASSWORD: "agence_staging_pwd_secure_2024"
  JWT_SECRET: "staging_secret_key_32chars_secure_!!"
