# Ingress local sans TLS/cert-manager, expose l'app sur http://localhost
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agence-ingress
  namespace: agence
  labels:
    app.kubernetes.io/part-of: agence-location
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
