apiVersion: v1
kind: Namespace
metadata:
  name: agence-dev
  labels:
    app.kubernetes.io/part-of: agence-platform
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: agence-staging
  labels:
    app.kubernetes.io/part-of: agence-platform
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: agence-prod
  labels:
    app.kubernetes.io/part-of: agence-platform
    environment: prod
