apiVersion: v1
kind: ServiceAccount
metadata:
  name: agence-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agence-read-config
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agence-read-config-binding
subjects:
  - kind: ServiceAccount
    name: agence-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agence-read-config
