apiVersion: v1
kind: Secret
metadata:
  name: agence-secrets
  labels:
    app: agence
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "agence"
  SPRING_DATASOURCE_PASSWORD: "change_me"
  POSTGRES_DB: "agence_location"
  POSTGRES_USER: "agence"
  POSTGRES_PASSWORD: "change_me"
  JWT_SECRET: "replace_me_super_secret_32_chars_min"
