apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agence
resources:
  - ../../base
images:
  - name: agence-backend:local
    newName: agence-backend
    newTag: local
  - name: agence-frontend:local
    newName: agence-frontend
    newTag: local
