grafana:
  enabled: true
  adminPassword: change_me_grafana
  sidecar:
    dashboards:
      enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.example.com
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.example.com

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - alertmanager.example.com
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.example.com
