kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: agence-dev
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 8080
        hostPort: 8080
        protocol: TCP
      - containerPort: 8081
        hostPort: 8081
        protocol: TCP
      - containerPort: 5432
        hostPort: 5432
        protocol: TCP
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
