apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: agence
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: agence-location
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
