apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: agence
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: agence-location
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
