apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agence-prod
resources:
  - ../../base
  - secret.yaml
patchesStrategicMerge:
  - patch-configmap.yaml
  - patch-ingress.yaml
  - patch-replicas.yaml
  - patch-hpa.yaml
images:
  - name: ghcr.io/alibd1990/agence-backend
    newTag: prod-latest
  - name: ghcr.io/alibd1990/agence-frontend
    newTag: prod-latest
