apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agence-ingress
spec:
  tls:
    - hosts:
        - app.example.com
        - api.example.com
      secretName: agence-prod-tls
  rules:
    - host: app.example.com
    - host: api.example.com
