apiVersion: v1
kind: Secret
metadata:
  name: agence-secrets
  namespace: agence-prod
  labels:
    app: agence
    environment: prod
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "agence_prod"
  SPRING_DATASOURCE_PASSWORD: "Prod@Secure#2024!KeyChange123456"
  POSTGRES_DB: "agence_location_prod"
  POSTGRES_USER: "agence_prod"
  POSTGRES_PASSWORD: "Prod@Secure#2024!KeyChange123456"
  JWT_SECRET: "Prod@JWT!Secret#Key2024$Secure%Tok"
