apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: agence
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: agence-location
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/agence_location
  SPRING_DATASOURCE_USERNAME: agence
  JWT_ACCESS_EXPIRATION: "900"
  JWT_REFRESH_EXPIRATION: "604800"
  CORS_ALLOWED_ORIGINS: http://localhost:8090
